### ISSUE TITLE
Vanilla transport support doesnt work with DCG,No option to disable DCG transport, No option for DCG Weather

### ISSUE THREAD

**Issue by Radeni** [nicholasclark-artist/DCG#100]
**Arma 3 Version:** 1.68
**CBA Version:** latest
**DCG Version:** 3.2.0
**Server Mods:**
- `@CBA_A3`
- `@dcg`

**Description:**
- When running DCG on a mission,vanilla transport support doesnt work. However if DCG mod isnt enabled or if it is but mission is played in singleplayer,support works just fine. (With DCG,once the helicopter lands to pick you up and you give it a place to go to,the heli wont take off,instead the pilot will just tell you that you are already at the destination)
-Also,there is no option to disable DCG transport
-There is no option to enable/disable and tweak DCG Weather

**Steps to reproduce:**
- set up helicopter transport support in editor with dcg mod enabled.
-test mission in singleplayer (because dcg doesnt work there) and support should work propertly (Helicopter takes off and goes where it should go)
-test mission in multiplayer and helicopter wont take off
**Where did the issue occur?**
- Self-Hosted Multiplayer / Editor (Multiplayer)

**RPT log file:**
[Arma3_x64_2017-03-29_21-07-45.txt](https://github.com/nicholasclark-artist/DCG/files/880562/Arma3_x64_2017-03-29_21-07-45.txt)

**Comment by nicholasclark-artist** [comment]
In terms of the DCG's transport system, it's not meant to have any integration with vanilla features. It's a closed system. I'm not exactly sure what kind of vanilla support you'd like to see.

You can disable any DCG addon in-game using CBA Settings. You can disable addons on the server or per mission through the editor. The image below shows *dcg_transport* disabled for a mission. The same is true for *dcg_weather*.

![disable_transport](https://cloud.githubusercontent.com/assets/16869278/24482178/004fd53c-14b5-11e7-8d68-ca193184ff5d.JPG)

**Comment by Radeni** [comment]
I swear to god im gonna go back to 1st grade elementary to learn how to read cause i couldnt see those. But when it comes to vanilla transport,I didnt want to add any feature,i was reporting that using vanilla system bugs out in a DCG mission and it used to work perfectly fine before 3.2.0
