### ISSUE TITLE
Lythium CfgWorld Errors

### ISSUE THREAD

**Issue by Radeni** [nicholasclark-artist/DCG#103]
**Arma 3 Version:** `1.68` (stable / rc / dev)
**CBA Version:** `3.2.1`
**DCG Version:** `3.2.0`

**Server Mods:**
`Html file provided`

**Description:**
DCG mod fails to initate and causes ACE 3 to stop working properly. Their settings also disappear from CBA Control configuration menu. I have tested this error multiple times and it only appears with DCG on the Lythium map specificly and not just in one scenario but in any, without DCG other mods work completely fine including ACE 3 and CBA. Here is the screenshot of the error that appeared as soon as the mission was loaded,before even starting.

![20170430180406_1](https://cloud.githubusercontent.com/assets/16863311/25567935/7d6ddf76-2df8-11e7-815b-e27a7c069691.jpg)

**Steps to reproduce:**
Simply try to run any scenario with DCG on the Lythium map (it can be as simple as having only the player on the map).
My own mission for testing:

[dcg_lythium.lythium.zip](https://github.com/nicholasclark-artist/DCG/files/967004/dcg_lythium.lythium.zip)
[modlist.zip](https://github.com/nicholasclark-artist/DCG/files/967010/modlist.zip)

**Where did the issue occur?**
Self-Hosted Multiplayer / Editor (Multiplayer)

**RPT log file:**
Will provide if needed

**Comment by nicholasclark-artist** [comment]
This issue occurs because of an error in this map's CfgWorlds config. One of the villages has a string for its position when it should be a number. I can add checks for this kind of error, but this is ultimately an issue with the map.

![lythium](https://cloud.githubusercontent.com/assets/16869278/25604320/26d030a8-2ec8-11e7-911c-2908f27ecbee.JPG)

**Comment by Radeni** [comment]
Alright,i opened an issue on their feedback tracker the same time i did this one. I will show them this and hopefully they'll fix it soon. If they don't i'll fix the config by myself but you could help me by telling me what to change to have it working.

**Comment by Mickyleitor** [comment]
Ey! Thank you for pointing this out. It's internally fixed in our dev branch of FFAAMOD.

**Comment by Radeni** [comment]
@Mickyleitor No problem but Greenberet has already fixed the issue and this works since the update 4 days ago when this issue was closed
