### ISSUE TITLE
Occupy task downsides and improvement suggestions

### ISSUE THREAD

**Issue by Radeni** [nicholasclark-artist/DCG#104]
**Arma 3 Version:** `1.68` (stable)
**CBA Version:** `3.2.1`
**DCG Version:** `3.2.0`

**Server Mods:**
- `@CBA_A3`
- `@dcg`

**Description:**
- When a friendly person or vehicle enters the area of the "Liberate location" task the notification that enemies are loosing control pops up and soon after the objective is completed.

**Steps to reproduce:**
A) Enter the liberate objective as infantry or
B) Enter in a vehicle (helicopter,car,plane)

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Multiplayer)

**Comment by nicholasclark-artist** [comment]
The occupy location script should only show said notification once the players have a stronger force in the area. If this is not the case I'll need to know the map and location name.

**Comment by Radeni** [comment]
It actually happened on all maps and any location that was tasked. But i think most of the locations were villages. I think the problem is that the Occupy count settings were removed. I noticed that its usually between 20 and 30 infantrymen and 1-2 ground vehicles.

**Comment by nicholasclark-artist** [comment]
The occupy addon uses the player count to determine the enemy count. I tested this yesterday on Tanoa and the task did not auto complete. In your mission, do any enemies actually spawn in the location? Do you have a rpt file from the mission?

**Comment by Radeni** [comment]
Yea they spawn i see them all from the distance. I think the problem could be the treshold for enemies left in the objective and their power.I guess if i kill a few of em as an infantryman or just enter the area with a high cost vehicle the "losing control" mesage is displayed. Ill have to do some more testing later.Hopefully ill find out something actually useful. I also hope that you add the enemy per player multiplier

**Comment by Radeni** [comment]
It seems that it actually works fine and the problem was:
Usually me and my group play as spec-ops with tactical movement and stuff and we usually engage enemies at 200+ meters. What happens is that we kill a lot of them (yet not too many compared to us) and once a team moves or a vehicle,the objective gets completed. There are a few notable things that make the objectives too easy:
1.  Low amount of vehicles 

2. _All of the infantry groups spawn in a single place **(Where they usually stay because of Dynamic simulation)**_

_Suggestions:_
-A multiplier setting for enemies (as suggested in #97 ) // x<y<z
`dcg_occupyMultiplier_village = x;`
`dcg_occupyMultiplier_city = y;`
`dcg_occupyMultiplier_capital = z`

-An optional setting for static amount of enemies like in previous versions,i.e:
`dcg_occpyCount_enable = 1;` //0 to disable,1 overrides multiplier and replaces it with a static count:
`dcg_infantryCount_village = x;`
`dcg_infantryCount_city = y;`
`dcg_infantryCount_capital = z;` and to the same for vehicles and air units (`dcg_vehicleCount_location` and `dcg_airCount_location`)

**Comment by nicholasclark-artist** [comment]
It's true that the occupy system does not trigger until a player actually enters the location. This should be addressed in future updates; however, to address your other concerns you can simply adjust the _Enemy Count Multiplier_ using CBA settings and increase the dynamic simulation range for your mission.

**Comment by Radeni** [comment]
yep,i kinda should've adressed this in #97 instead of here. What i wanted to say before but forgot is that there's space for a Dynamic simulation delay so that the units spawned have some time to roam around before their simulation is disabled. (30 - 60 seconds possibly)
