### ISSUE TITLE
Translation of tasks

### ISSUE THREAD

**Issue by Ghosto27** [nicholasclark-artist/DCG#136]
**Arma 3 Version:** `x.xx` (**stable** / rc / dev)  
**CBA Version:** `x.x.x`  
**DCG Version:** `3.2.0`  

**Server Mods:**

- `@CBA_A3`
- `@dcg`
- and others

**Description:**

- I tried to traslate some of tasks descriptions. But after pbo repack it cant work.

**Steps to reproduce:**

- depbo dcg_task.pbo. Translate desriptions in dcg_task\functions files. pack dcg_task.pbo again.

**Where did the issue occur?**

- Dedicated 

**RPT log file:**

- https://gist.github.com/Ghosto27/2269d7ec011380e372ee99cbde3a9afc

**Comment by nicholasclark-artist** [comment]
What do you mean by it doesn't work? 

I don't have much experience with translations, but the rpt file shows the task addon is running at [line 12302](https://gist.github.com/Ghosto27/2269d7ec011380e372ee99cbde3a9afc#file-gistfile1-txt-L12302). However, this is followed by a script error, which may be the issue.

**Comment by Ghosto27** [comment]
I think it accure with wrong DePbo and MakePbo operations with Mikero tools (do you use it?).
After repacking pbo files that in logs I see problems like (on Occupy module example):
16:25:27 Warning Message: Script \d\dcg\addons\occupy\XEH_preInit.sqf not found
16:25:27 Warning Message: Script \d\dcg\addons\occupy\XEH_postInit.sqf not found

and that module dont work.

**Comment by nicholasclark-artist** [comment]
Yeah, I use Mikero's tools. You may be getting that error because our development environments are configured differently. All of DCG's file paths are set to work with a P drive similar to ACE's setup, [ACE3 Dev Environment](https://ace3mod.com/wiki/development/setting-up-the-development-environment.html).

**Comment by Ghosto27** [comment]
I managed to pack the files. Using ExtractPBO and MakePbo with keys like yours in the make.py file "-P", "- A", "- G", "- N". I successfully translated the tasks texts. Thanks for attention.

**Comment by nicholasclark-artist** [comment]
glad to hear it
