### ISSUE TITLE
Cant seem to get the east unit pool to change 

### ISSUE THREAD

**Issue by onedigita** [nicholasclark-artist/DCG#32]
Ive tried modding this so that it will spawn different units but it continues to spawn csat units

**Comment by onedigita** [comment]
Specifically i cannot spawn cup units

lass dcg_main_unitPoolEast {
	typeName = "ARRAY";
	typeDetail = "POOL";
	value[] = {
		{"ALL","CUP_O_TK_INS_SOLIDER_TL","CUP_O_TK_INS_Solider","CUP_O_TK_INS_medic","CUP_O_TK_INS_bomber","CUP_O_TK_INS_rpg","CUP_O_TK_INS_Sniper","CUP_O_TK_INS_Solider_aat","CUP_O_TK_INS_Solider_gl","CUP_O_TK_INS_Solider_mg","CUP_O_TK_INS_ar","CUP_O_TK_INS_Solider_aa","CUP_O_TK_INS_mechanic","CUP_O_TK_INS_Solider_endfield"}
	};
};

**Comment by onedigita** [comment]
this was changed in the userconfig file that the dedicated server runs

**Comment by nicholasclark-artist** [comment]
Thanks for pointing this out @onedigita. There was an error in the way the server addon was packaged. It's fixed for 3.1.0.5.
