### ISSUE TITLE
FUNC(findPosRural) not suitable for all maps

### ISSUE THREAD

**Issue by DrHardSlump** [nicholasclark-artist/DCG#49]
Hi!!! first, congrats for your work
second, i move all your stuff on chernarus and works fine. but the base type missions (cache, officer, artillery) only appear at the same spot.
is posible to add marks on the map to force to appear randomly?
thx

**Comment by nicholasclark-artist** [comment]
Thanks @DrHardSlump. 

These tasks use [FUNC(findPosRural)](https://github.com/nicholasclark-artist/DCG/blob/master/addons/main/functions/fnc_findPosRural.sqf) to locate a random position for the base. I haven't tested DCG on Chernarus in a while, so I'll take a look.

**Comment by nicholasclark-artist** [comment]
fixed 
- replaced by [FUNC(findPos)](https://github.com/nicholasclark-artist/DCG/blob/master/addons/main/functions/fnc_findPos.sqf). New function has a better success rate for all terrain types and handles rural as well as populated positions
