### ISSUE TITLE
RPT Performance warning

### ISSUE THREAD

**Issue by jus61** [nicholasclark-artist/DCG#52]
RPT Info:
`19:04:31 Performance warning: SimpleSerialization::Write 'dcg_fob_location' is using type of ',LOCATION' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
`

**Comment by nicholasclark-artist** [comment]
This is due to sending one location as a publicVariable at mission start. It isn't something to worry about.
