### ISSUE TITLE
ID error upon requesting control of FOB

### ISSUE THREAD

**Issue by tbeswick96** [nicholasclark-artist/DCG#55]
I am not 100% certain of this, but I think this occurs when whoever is in control of the FOB has disconnected, and someone tries to take control of the FOB.

```
0:20:20 Error in expression <
                -1 = 1;
                [player,1,-1] call dcg_main_fnc>
0:20:20   Error position: <= 1;
                [player,1,-1] call dcg_main_fnc>
0:20:20   Error Missing ;
```

This results in no-one being able to take control of the FOB (even admin).
This might be because without the ID of the player who was in control (who has since disconnected), it returns to the default:

```
GVAR(response) = -1;
GVAR(ID1) = -1;
GVAR(ID2) = -1;
```

**Comment by nicholasclark-artist** [comment]
I'll look into it. Please provide the rpt file with the listed error.

**Comment by tbeswick96** [comment]
Full RPT: https://gist.github.com/tbeswick96/f44b3bfce5fd104a249b9a121c20ad84

**Comment by nicholasclark-artist** [comment]
This should be fixed now, but I'll leave the issue open for the time being. I believe the problem was an error in the way the request actions were added and removed in [FUNC(handleRequest)](https://github.com/nicholasclark-artist/DCG/blob/master/addons/fob/functions/fnc_handleRequest.sqf).
