### ISSUE TITLE
Serverconfig problems on unitPool

### ISSUE THREAD

**Issue by DrHardSlump** [nicholasclark-artist/DCG#59]
Hello!!!
Me again...
In the serverconfig from dgc, i change the enemies they spawn on missions. But don't work. The classname are correct (i check two times)...

class dcg_main_unitPoolEast {
	typeName = "ARRAY";
	typeDetail = "POOL";
	value[] = {
		{"ALL","IP_O_soldier_AR_FST","IP_O_medic_FST","IP_O_soldier_exp_FST","IP_O_soldier_GL_FST","IP_O_soldier_AT_FST","IP_O_soldier_repair_FST","IP_O_soldier_AAR_FST","IP_O_soldier_M_FST","IP_O_soldier_FST","IP_O_support_AMG_FST","IP_O_support_MG_FST","IP_O_engineer_FST","IP_O_Soldier_AA_FST"}
	};
};

Thx again...

**Comment by nicholasclark-artist** [comment]
make sure your dcg_server.pbo is set up correctly. Check the wiki

**Comment by DrHardSlump** [comment]
Ok, that's the problem... Now works
In the meantime i try to edit the pbo files (dcg_occupy and change the spawn count) with PBOmanager (you know extract, edit the config file with notepad++ and convert again to pbo. Then don't work... Only change the enemy count on villages and citys.

Thx

**Comment by nicholasclark-artist** [comment]
those settings are exposed in the userconfig file, you can change them there. I added a short description of all the settings [here](https://github.com/nicholasclark-artist/DCG/wiki/Addon-List)

**Comment by DrHardSlump** [comment]
Done!!! Thx clark!!!
