### ISSUE TITLE
Vehicle Respawn

### ISSUE THREAD

**Issue by DrHardSlump** [nicholasclark-artist/DCG#71]
**Arma 3 Version:** `last` stable
**CBA Version:** `last`
**DCG Version:** `3.1.0.6`

**Server Mods:**
- @CBA_A3
- @dcg
- @RHS
- @VSM
- @ACE
- @Chernarus, Takista, etc...
- custom serverconfig with RHS units

**Description:**
- Vehicle enemies respawn on air, then crash wen hit the ground

**Steps to reproduce:**
- Vehicle patrol spawn or spawn on village/city/capital

**Where did the issue occur?**
- Dedicated

**Comment by nicholasclark-artist** [comment]
fixed
