### ISSUE TITLE
CBA control keys don't do anything, Issues with Ace + Incompatible Zeus?

### ISSUE THREAD

**Issue by Radeni** [nicholasclark-artist/DCG#73]
**Arma 3 Version:** `1.64` 
**CBA Version:** `3.1.2`
**DCG Version:** `3.1.0.6`

**Server Mods:**
- @cba_a3
- @dcg
- @ace

**Description:**
I noticed 1 very irritating thing having to do with the FOB system combined with @ace . When using ace mod together with DCG trying to build the FOB from the FOB menu most likely crashes my game. I have also noticed that some of the actions for the FOB system don't work if using keys (the ones defined in cba configure addons).

What i am asking is if its possible to create a new dcg setting called dcg_enable_ace in order to decide if or if not dcg will use Ace or an optional .pbo to add if you want to use ace. Also i am not sure why wouldn't the CBA keys work but currently the only one i found working is the request fob control.

I also want to ask, is an editor placed Zeus incompatible with the FOB Zeus. Maybe its only when the same person tries both.

**Steps to reproduce:**

**Where did the issue occur?**
- Dedicated server

**Comment by nicholasclark-artist** [comment]
Please use the template for future bug reports as it's very hard to track down issues without the necessary info. I've edited your post to include the proper categories. Update the post if any info is incorrect.

**Comment by nicholasclark-artist** [comment]
### Broken keybindings and missing actions 
fixed, see [#74](https://github.com/nicholasclark-artist/DCG/issues/74) for more info

### FOB related crashes 
In my testing, FOB related crashes only occurred when the FOB controller tried to open the build interface in certain situations such as...
- in a vehicle
- camera not focused on player (camera on UAV, camera on controlled zeus unit, etc)
- map open 

If I'm missing a scenario to check, please provide a detailed description of the situation
