### ISSUE TITLE
Adding Zeus to DCG missions

### ISSUE THREAD

**Issue by nikoyan** [nicholasclark-artist/DCG#75]
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.1.2`
**DCG Version:** `3.1.0.6`

**Server Mods:**
- `@CBA_A3`
- `@dcg`

**Description:**
How to add ZEUS to the mission? (for being used with Ares-Achilles mod) Upon editing with eden editor to add gamemaster, the filesize of the SQF decreases from 140kb to 131kb. The mission starts, but ace does not initialise, tasks are not created and the arsenal does not work (initialise). Any ideas would be appreciated!

**Steps to reproduce:**
1) Load arma with only CBA enabled
2) Start eden editor
3) Load the dcg_west mission
4) Add a game master module and sync to plt_co
5) Set owner to "plt_co" in Game Master module
6) Export to MP
7) Test in Dedicated and Self-Hosted MP

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer

**Comment by celticalliance** [comment]
We have recently discovered the issue nikoyan describes, he is a member of our clan, is not an issue that requires fixing. We actually caused the issue ourselves, without realising it at first.

We are using the dcg_main_init option in the server config file to make the DCG mod run on specific missions only, and we forgot to add the name of the mission we created to this option. As such the DCG mod was not running, which made us assume that placing some Zeus Game Master modules broke DCG.
