### ISSUE TITLE
CHECK_ADDON_2 1 -> true

### ISSUE THREAD

**Issue by tbeswick96** [nicholasclark-artist/DCG#79]
To fit with the change with CBA settings, the CHECK_ADDON_2 macro part {EGVAR(VAR,enable) isEqualTo 1} needs to be changed to {EGVAR(VAR,enable) isEqualTo true}, else the mission data won't save. https://github.com/nicholasclark-artist/DCG/blob/master/addons/main/script_macros.hpp#L95

**Comment by nicholasclark-artist** [comment]
Thanks 👍  it's been a while since I've pushed changes, fixed now
