### ISSUE TITLE
Question and suggestion for the Resscue VIP task

### ISSUE THREAD

**Issue by Radeni** [nicholasclark-artist/DCG#80]
I have finally realized that you require ACE in order to complete the task. I am guessing you are supposed to use Cable ties to transport the VIP to the location set in the task.

My question is how is the mission completed?I have transported the VIP to the location many times and never completed it. 
Im suggesting that you should make a different way for the handling of the VIP:
-Make the VIP a captured blufor unit
-Set him as captive so he doesnt get shot by Opfor (vip setCaptive true;)
-Put him in the animation so he is tied up just like he is right now
-Add an action to the VIP which would then make the VIP in a normal animation so he can move,and it would make the VIP join the player's group,that way the VIP will follow the player

I think you could easily set up what i suggested. It should really help handling the VIP isntead of Ace but please explain me where to bring the VIP to.

**Comment by nicholasclark-artist** [comment]
I've made changes to the VIP task to make it more intuitive and compatible with the vanilla game. These updates will be part of the 3.2.0 release.

**Comment by Radeni** [comment]
Awesome!
