### ISSUE TITLE
SQF/Scripting Compatibility

### ISSUE THREAD

**Issue by dominicporteous** [nicholasclark-artist/DCG#81]
Is there an easy way to trigger events such as new secondary objectives from SQF?

Cant seem to find any global function definitions to call.. (was trying e.g. dcg_task_fnc_create etc.)

**Comment by nicholasclark-artist** [comment]
To spawn a random task you can use [FUNC(select)](https://github.com/nicholasclark-artist/DCG/blob/master/addons/task/functions/fnc_select.sqf), however, you'll need to cancel the current task before doing so. 

Currently, there isn't an elegant way to call a specific task, but each task function is saved to a global variable, so it's possible to use `[] spawn (missionNamespace getVariable [_task,{}]);`. All task variable names are saved to **dcg_task_primaryList** and **dcg_task_secondaryList**.
