### ISSUE TITLE
Feature Request: Module Based settings

### ISSUE THREAD

**Issue by sargken** [nicholasclark-artist/DCG#82]
Remove the use of description.ext for mission based settings and have them all converted to modules so the user in the editor makes it easy. I forked your repo and started looking into doing this. Could you confirm to me that it would be possible. I also may be asking some questions on your code to help me convert it over if you like the idea.

**Comment by nicholasclark-artist** [comment]
In 3.2.0, most of the settings are implemented using CBA's settings framework. This allows DCG to be adjusted in-game. I've considered using modules, but they add a dependency in the mission sqm. Keeping DCG as modular as possible is one of my goals, so making a mission dependent on DCG isn't suitable.

**Comment by sargken** [comment]
Ok then feel free to close this issue. I did not know that you were going to use CBA settings.

**Comment by nicholasclark-artist** [comment]
No prob, stay tuned :smile:
