### ISSUE TITLE
EDEN Support

### ISSUE THREAD

**Issue by nicholasclark-artist** [nicholasclark-artist/DCG#85]
### EDEN Support
- Add DCG tools to EDEN editor menu bar
     - Export unit pools through EDEN editor selections 
     - Export default userconfig settings 
- Consider adding more EDEN integration

**Comment by nicholasclark-artist** [comment]
[img_exportPool]: https://github.com/nicholasclark-artist/DCG/wiki/media/tool_export_pool.jpg "img_exportPool"

added first pass

![][img_exportPool]

**Comment by DrHardSlump** [comment]
Nice and easy!! this work with enemy side i suppose... how much need to wait for 3.2??¿!!! hype...
