### ISSUE TITLE
Change enemy factions on mission start

### ISSUE THREAD

**Issue by tenondra** [nicholasclark-artist/DCG#88]
Hey, would it be possible to create enemy factions, so you can change them while starting the mission? currently, we can only have one faction configured in serverconfig. I wonder, if its possible like it used to be (and i'm just missing something). Thanks!

**Comment by nicholasclark-artist** [comment]
3.2.0 implements [CBA's setting framework](https://github.com/CBATeam/CBA_A3/wiki/Settings-System), which allows you to configure the enemy side in-game. Factions are a little different; they can be adjusted using unitpools in serverconfig.hpp.

For example, in 3.2.0, if I want to set NATO units as the enemy, I would select WEST as the enemy side in-game and I'd place NATO units in dcg_main_unitPoolWest in serverconfig.hpp.

These updates will be reflected in the documentation once 3.2.0 is released.
