### ISSUE TITLE
Arma 3 Launcher required Mod issue

### ISSUE THREAD

**Issue by redeye83** [nicholasclark-artist/DCG#90]
**DCG Version:** `3.1.0.6`

**Description:**
When ran on a server using sig check players that run the addon, albeit unnecessarily, will get kicked as the addon is not signed.
When players use the launcher to connect to the server it shows as a required addon so people try and run it.

**Steps to reproduce:**
Look at a server running the addon in the launcher

**Where did the issue occur?**
Dedicated Server

**Images**
https://puu.sh/uwI2Z/cb9a049615.png
![ss 2017-03-06 at 04 04 40](https://cloud.githubusercontent.com/assets/3596553/23663331/2d0d3604-034a-11e7-90fc-c46605af89bd.png)

**Comment by Radeni** [comment]
This mod shouldn't be in the normal mods section,when you initialize your server there are mods but there are also server mods.The server ones wont be required by the clients.I take it you know how to config a server init so here is the command to add to it:
-serverMod= @Dynamic Combat Generator (Or whichever is your foldername of the mod)

**Comment by redeye83** [comment]
Did not even realise this was a thing!
