### ISSUE TITLE
Transport route broken

### ISSUE THREAD

**Issue by nicholasclark-artist** [nicholasclark-artist/DCG#91]
**Arma 3 Version:** `1.68` (stable)
**CBA Version:** `3.2.1`
**DCG Version:** `3.2.0`

**Server Mods:**
- `@CBA_A3`
- `@dcg`

**Description:**
- Upon landing at the extraction position, the transport vehicle will not continue its route while a player is in the vehicle's cargo.

**Steps to reproduce:**
- Call transport via action menu
- Board transport 
- Signal take off

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Multiplayer)

**Comment by Radeni** [comment]
I dont think there is need for integrated transport when its very easy to set up vanilla support module

**Comment by nicholasclark-artist** [comment]
You'd be surprised how reluctant some people are to open the editor :cry:

Anways, fixed. The issue was caused by the transport group being cached while enroute.
