### ISSUE TITLE
Approval regions don't cover entire map

### ISSUE THREAD

**Issue by nicholasclark-artist** [nicholasclark-artist/DCG#92]
**Arma 3 Version:** `1.68` (stable / rc / dev)
**CBA Version:** `3.2.1`
**DCG Version:** `3.2.0`

**Server Mods:**
- `@CBA_A3`
- `@dcg`

**Description:**
- Depending on the map, the *dcg_approval* regions do not cover the entire map. Tested on Tanoa (eastern most terrain)

**Steps to reproduce:**
- Run DCG on Tanoa
- Move to eastern side of island
- Notice Check Region action does not work

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Multiplayer)

**Comment by Radeni** [comment]
could it have to do with the grid cell (10x10km) not being complete in that part of the map?

**Comment by nicholasclark-artist** [comment]
Yeah, it's basically because worldSize is a weird number. I'm separating the map into 2km grid blocks in [FUNC(handleLoadData)](https://github.com/nicholasclark-artist/DCG/blob/master/addons/approval/functions/fnc_handleLoadData.sqf), the current method doesn't divide nicely on some maps.

**Comment by nicholasclark-artist** [comment]
fixed in #128
