### ISSUE TITLE
How do I use IEDs as a mission maker?

### ISSUE THREAD

**Issue by WSIContractor** [nicholasclark-artist/DCG#93]
**Arma 3 Version:** `1.68` (stable)
**CBA Version:** `x.x.x` Current
**DCG Version:** `x.x.x` Current

**Server Mods:**
- `@CBA_A3`
- `@dcg`

**Description:**
- As a mission maker want to understand how to add in IEDs?

**Steps to reproduce:**
- NA

**Where did the issue occur?**
- Editor (Multiplayer)

**RPT log file:**
- NA

**Comment by nicholasclark-artist** [comment]
IEDs are automatically placed as long as you have the ied addon enabled through the settings framework.
