### ISSUE TITLE
How do I select different OPFOR?

### ISSUE THREAD

**Issue by WSIContractor** [nicholasclark-artist/DCG#94]
How do I select different opfor? Is it via the userconfig on the server? Can I use mission parameters to set it instead based on the OPFOR mods loaded?

Thanks.

**Comment by nicholasclark-artist** [comment]
Check out the [Settings Framework](https://github.com/nicholasclark-artist/DCG/wiki/Settings-Framework)  page and the [EDEN Editor](https://github.com/nicholasclark-artist/DCG/wiki/EDEN-Editor) page for info on how to handle unitpools. Basically, export a pool from the editor and paste into the userconfig file. You can also paste the data into the description.ext if you need to for whatever reason. These settings aren't editable through mission parameters.

**Comment by WSIContractor** [comment]
okay, that is a pity. It would be easier to select the enemy in mission parameters as oppose to exporting which is a bit of a pain.

**Comment by nicholasclark-artist** [comment]
mission parameters don't support array data types, only integers. You can export the pools through the editor and assign them to specific maps or missions, so you don't have to mess with the userconfig often.
