### ISSUE TITLE
Mission files (mission.sqm) are binarized in the samples

### ISSUE THREAD

**Issue by WSIContractor** [nicholasclark-artist/DCG#96]
You might want to turn on the binarize mission when saving them out. Right now in the source code and in the zip release the mission.sqm file in the Altis sample mission is binarzied. It would be great to get a non-binarized version.

**Comment by nicholasclark-artist** [comment]
I included unpacked versions of the missions. You should be able to open those in the editor and uncheck binarize. `EDEN Editor >> Attributes >> General >> Binarize the Scenario File`
