### ISSUE TITLE
Occupy not working,constant errors,poor performance

### ISSUE THREAD

**Issue by Radeni** [nicholasclark-artist/DCG#98]
**Arma 3 Version:** 1.68
**CBA Version:** Latest
**DCG Version:** 3.2

**Description:**
Occupy locations aren't spawning even tho they're enabled in addon settings. Mission spams constant errors which affect performance (3.1.0 had 60-70 fps, 3.2.0 has 30-40 on the same mission file)

**Steps to reproduce:**
- To be able to view the errors,run the mission from 3den editor as a multiplayer scenario (3DEN>Play>Play in multiplayer) 
**Where did the issue occur?**
-  Self-Hosted Multiplayer / Editor (Multiplayer)

**Comment by nicholasclark-artist** [comment]
I'm not seeing these errors. Are you using the latest version of the mission template? Send me an [rpt file](https://community.bistudio.com/wiki/Crash_Files) from the mission with the issue.

**Comment by Radeni** [comment]
[Arma3_x64_2017-03-28_17-52-01.txt](https://github.com/nicholasclark-artist/DCG/files/879501/Arma3_x64_2017-03-28_17-52-01.txt)

**Comment by Radeni** [comment]
I think its because of the old mission template. Ill set up a new one and try it out

**Comment by nicholasclark-artist** [comment]
You'd need to remove the -noLogs startup param for the rpt to generate any useful info. You can resend an rpt without -noLogs, but I think it's due to using the old template.

**Comment by Radeni** [comment]
yea,i tried the new one and it was fine,performance and mission wise

**Comment by nicholasclark-artist** [comment]
sounds good 😄
